### ISSUE TITLE
Should we remove the Sentiment part of the events in the Timeline?

### ISSUE THREAD

**Issue by AndyFou** [AndyFou/refugee-crisis#14]

**Comment by AndyFou** [comment]
It's all-neutral either way !

**Comment by N1h1l1sT** [comment]
Granted, it is quite unappealing and fairly unfavourable for an Affective Analysis, however, effacing it could be construed as a lie by omission, so...
I move that the sentiment remain

**Comment by N1h1l1sT** [comment]
(I thought that "Close and comment" meant that the comment-editing thingy closes - didn't know it'd close the issue. I apologise. I re-opened it)

**Comment by AndyFou** [comment]
hahah never mind! actually you may close the issue now, as the question is anwered! ^^
